X=set('spam');
Y={'h', 'a', 'm'};
print(X, Y);
print(X & Y);
print(X | Y);
print(X-Y);
print({x**2 for x in [1,2,3,6]});
print(1/3);
print(2/3+1/2);
import decimal;
d=decimal.Decimal('3.141');
print(d+1);
decimal.getcontext().prec=2;
decimal.Decimal('1.00')/decimal.Decimal('3.00');

from fractions import Fraction;
f=Fraction(2,3);
print(f+1);
print(f+Fraction(1,2));
print(1>2, 1<2);
print(bool('spam'));
X=None;
print(X);
L=[None]*100;
print(L);
