print('shrubbery', "shurubbery");
print('knight"s', "knight's");
print("Meaning"'of'"life");
print('a\tb\nc');
print('\a');
print('\0a\0b');
print(len('abc'));
print('abc'+'def');
print('Ni!'*4);
myjob="hacker";
for c in myjob: print(c, ' ')
print('k' in myjob);
print(str('spam'), repr('spam'));
S='66';
I=1;
print(int(S) + I);
print(S+str(I));
print(str(3.16), float('1.5'));
i='5';
print(chr(ord(i)+1));
print(chr(ord(i)+2));
print('*******************');
b='1101';
i=0;
while b!='':
	i=i*2+(ord(b[0])-ord('0'));
	b=b[1:];

print(bin(i));
print(i);
print(b);
print(int('1101', 2));
print(bin(13));
print('*****************');
s='splot'
s=s.replace('pl', 'pamal');
print(s);
print('That is %d %s bird!' %(1, 'lovely'));
print('this is {0} {1}  bird!'.format(1, 'lovely'));
s='spammy';
s=s[:3]+'xx'+s[5:];
print(s);
print('***********replace*************');
print(s.replace('xx', 'mm'));
print('************************');
s='xxxxxSpamxxxxxxspamxxxxxxx';
where=s.find('Spam');
print(where);
s=s[:where]+'EGGS'+s[where+4:];
print(s);
print('*********************');
s='spammy';
l=list(s);
print(l);
l[3]='x';
l[4]='x';
print(l);
s=''.join(l);
print(s);
